### PR TITLE
ENH: Add parameter to ignore specified warnings

### PR DESCRIPTION
**Pull request by tbirdso**
Closes https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/issues/26

Pending testing.

### CODE REVIEW

**Comment by tbirdso** [comment]
Successful test: https://github.com/tbirdso/ITKCleaver/actions/runs/3659581535/jobs/6185738080

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
@tbirdso thanks!!

**Comment by thewtex** [comment]
I am not sure what happened with GitHub, but this was merged.

**Comment by tbirdso** [comment]
Thanks @thewtex , haven't seen Github fail to close a merged PR before, weird 🤔

**Pull request closed without merging**
