### PR TITLE
ENH: Bump for ITK v5.3rc04.post4

### PR DESCRIPTION
**Pull request by tbirdso**
Pending successful ITKSplitComponents test workflow run

https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3472832027

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by tbirdso** [comment]
@thewtex Update on current status:
- Linux build archives for v5.3rc04.post4 do not contain Python 3.11 sources and Linux Python 3.11 wheels are not present on PyPI (https://pypi.org/project/itk/5.3rc4.post4/#files) for the release. I have identified the issue in ITKPythonPackage, am rebuilding archives, and will submit a patch to ITKPythonPackage shortly.
- I am concerned by Windows failures in ITKSplitComponents:
```
ITKCommon-5.3.lib(itkSingleton.cxx.obj) : error LNK2019: unresolved external symbol __std_init_once_link_alternate_names_and_abort referenced in function "void __cdecl std::call_once<class <lambda_765cdde47a138f6f7443124c5cc7592a> >(struct std::once_flag &,class <lambda_765cdde47a138f6f7443124c5cc7592a> &&)" (??$call_once@V<lambda_765cdde47a138f6f7443124c5cc7592a>@@$$V@std@@YAXAEAUonce_flag@0@$$QEAV<lambda_765cdde47a138f6f7443124c5cc7592a>@@@Z)
ITKCommon-5.3.lib(itkImageSourceCommon.cxx.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort
ITKCommon-5.3.lib(itkThreadPool.cxx.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort
C:\P\IPP\ITK-win_37-x64\Wrapping\Generators\Python\itk\_SplitComponentsPython.pyd : fatal error LNK1120: 1 unresolved externals
```
This error occurs in the Python 3.7 build. I do not see any recent changes in `itkThreadPool`, and from the error message it seems like this is an STL compiler issue. There is some discussion around MSVC static library changes from earlier this year in https://developercommunity.visualstudio.com/t/__imp___std_init_once_complete-unresolve/1684365, though it sounds like those were resolved.

@thewtex @dzenanz Have either of you seen this issue before and/or have thoughts on steps to identify the cause? Could this be related to how v5.3rc04.post4 Windows build archives were generated?

**Comment by dzenanz** [comment]
I have not seen this issue before. By a quick search, it does not seem to be common.

**Comment by thewtex** [comment]
@tbirdso yes, it is likely compiler versions -- I created the  v5.3rc04.post4 on a system with VS 2022 -- the previous were created on VS 2019 (this is not the same as the MSVC toolchain version, but likely an earlier version). @tbirdso could you please try `windows-2022` actions runner: https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

**Comment by tbirdso** [comment]
ITKSplitComponents is green: https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3492450754/jobs/5846243542

Proceeding with merge

**Pull request merged**
